SoftwareUniversity_WebApp/Controllers/PlayerController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using SoftwareUniversity_WebApp.Models;
using WebApp.Core.Interfaces;
using WebApp.Core.Models;

namespace SoftwareUniversity_WebApp.Controllers
{
    public class PlayerController : Controller
    {
        private readonly IPlayerService _playerService;
        private readonly IRepository _repository;
        private readonly IValidationService _validator;
        private readonly ITeamService _teamService;

        public PlayerController(IPlayerService playerService, IRepository repository, IValidationService validator, ITeamService teamService)
        {
            _playerService = playerService;
            _repository = repository;
            _validator = validator;
            _teamService = teamService;
        }

        public IActionResult Add()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var teams = _repository.GetEntitiesFromDb(userId);
            return View(teams);
        }

        [HttpPost]
        public IActionResult Add(AddPlayerViewModel model)
        {
            (bool passed1, string error1) = _validator.ValidateModel(model);
            if (passed1)
            {
                if (_playerService.CreatePlayer(model))
                {
                    return RedirectToAction("Home", "Home");
                }

                return RedirectToAction("Error", "Home", new{error1});
            }

            return RedirectToAction("Error", "Home", new { error1 });
        }

        public IActionResult ViewInfo(string id)
        {
            var player = _playerService.FindPlayer(id);

            return View(player);
        }

        public IActionResult Edit(string id)
        {
            var player = _playerService.FindPlayer(id);
            ViewData["team"] = _teamService.FindTeamForPlayer(player)
            return View(player);
        }

        [HttpPost]
        public IActionResult Edit(PlayerViewModel model)
        {
            (bool passed1, string error1) = _validator.ValidateModel(model);
            if (ModelState.IsValid)
            {
                if (_playerService.EditPlayer(model))
                {
                    return RedirectToAction("Home", "Home");
                }

                return RedirectToAction("Error", "Home", new { error1 });
            }

            return RedirectToAction("Error", "Home", new { error1 });
        }

        public IActionResult Remove(string id)
        {
            var player = _playerService.FindPlayer(id);

            return View(player);
        }

        [HttpPost]
        public IActionResult Remove(PlayerViewModel model)
        {
            if (_playerService.RemovePlayer(model.Id))
            {
                return RedirectToAction("Home", "Home");
            }

            return RedirectToAction("Error", "Home");
        }
    }
}

SoftwareUniversity_WebApp/Controllers/TeamController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApp.Core.Interfaces;
using WebApp.Core.Models;

namespace SoftwareUniversity_WebApp.Controllers
{
    public class TeamController : Controller
    {
        private readonly ITeamService _teamService;
        private readonly IPlayerService _playerService;
        private readonly IValidationService _validator;
        private readonly UserManager<IdentityUser> _userManager;

        public TeamController(ITeamService teamService, UserManager<IdentityUser> userManager, IPlayerService playerService, IValidationService validator)
        {
            _teamService = teamService;
            _userManager = userManager;
            _playerService = playerService;
            _validator = validator;
        }
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddTeamViewModel model)
        {
            (bool passed1, string error1) = _validator.ValidateModel(model);
            if (ModelState.IsValid)
            {
                (bool passed, string error) = _teamService.CreateTeam(model);

                if (passed = true)
                {
                    return RedirectToAction("Home", "Home");
                }
                else
                {
                    return RedirectToAction("Error", "Home", new { error1 });
                }
            }
            else
            {
                return RedirectToAction("Error", "Home", new { error1 });
            }
        }

        public IActionResult ViewInfo(string id)
        {
            var team = _teamService.FindTeam(id);
            ViewData["players"] = _playerService.GetPlayersByTeam(id);

            return View(team);
        }

        public IActionResult Edit(string id)
        {
            var team = _teamService.FindTeam(id);
            ViewData["players"] = _playerService.GetPlayersByTeam(id);
            return View(team);
        }

        [HttpPost]
        public IActionResult Edit(TeamViewModel model)
        {
            (bool passed1, string error1) = _validator.ValidateModel(model);
            if (ModelState.IsValid)
            {
                if (_teamService.EditTeam(model))
                {
                    return RedirectToAction("Home", "Home");

                }
                return RedirectToAction("Error", "Home", new { error1 });

            }
            return RedirectToAction("Error", "Home", new { error1 });
        }

        public IActionResult Remove(string id)
        {
            var team = _teamService.FindTeam(id);
            return View(team);
        }

        [HttpPost]
        public IActionResult Remove(TeamViewModel model)
        {
            if (_teamService.RemoveTeam(model.Id))
            {
                return RedirectToAction("Home", "Home");
            }
            return RedirectToAction("Error", "Home");
        }
    }
}

SoftwareUniversity_WebApp/Views/Team/Add.cshtml
@using WebApp.Core.Interfaces
@using Microsoft.AspNetCore.Identity

@{
    ViewData["Title"] = "Add Team";
}

@inject UserManager<IdentityUser> userManager
@{
    var user = userManager.GetUserAsync(User);
    var userId = user.Result.Id;
}

<link rel="stylesheet" href="/css/Team/nicepage.css" media="screen" asp-append-version="true" >
<link rel="stylesheet" href="/css/Team/AddTeam.css" media="screen" asp-append-version="true">

<body class="u-body u-xl-mode">
    <section class="u-clearfix u-section-1" id="sec-9bb9">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-container-style u-expanded-width u-group u-shape-rectangle u-group-1">
          <div class="u-container-layout u-container-layout-1">
            <div class="u-form u-form-1">
                   <form method="POST" class="u-clearfix u-form-spacing-10 u-form-vertical u-inner-form" source="email" name="form" style="padding: 10px;">
                    
                    <div class="u-form-group u-form-name">
                      <label for="name-8673" class="u-label">Name</label>
                      <input type="text" placeholder="Enter your Name" id="name-8673" name="Name" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required="">
                    </div>
                       <div class="u-form-email u-form-group">
                           <label for="email-8673" class="u-label">AgeSection</label>
                           <input type="number" placeholder="Enter Age Section" id="email-8673" name="AgeSection" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required="" spellcheck="false">
                       </div>
                       <input name="UserId" type="hidden" value="@userId" />
                       <div class="u-align-center u-form-group u-form-submit">
                           <button id="login-submit" type="submit" class="w-100 btn btn-lg btn-primary">Add</button>
                       </div>
                   </form>
            </div>
          </div>
        </div>
      </div>
    </section>
</body>

SoftwareUniversity_WebApp/Views/Team/Edit.cshtml
@using WebApp.Core.Interfaces
@using Microsoft.AspNetCore.Identity
@using WebApp.Core.Models
@inject UserManager<IdentityUser> userManager
@{
    var user = userManager.GetUserAsync(User);
    var userId = user.Result.Id;
}

@{
    ViewData["Title"] = "Player Info";
    IEnumerable<PlayerViewModel> players = ViewData["players"] as IEnumerable<PlayerViewModel>;
}
@model IQueryable<WebApp.Core.Models.TeamViewModel>

<link rel="stylesheet" href="/css/Team/nicepage.css" media="screen" asp-append-version="true" >
<link rel="stylesheet" href="/css/Player/EditPlayer.css" media="screen" asp-append-version="true">

<body class="u-body u-xl-mode">
    <section class="u-clearfix u-section-1" id="sec-9bb9">
        <div class="u-clearfix u-sheet u-sheet-1">
            <div class="u-container-style u-expanded-width u-group u-shape-rectangle u-group-1">
                <div class="u-container-layout u-container-layout-1">
                    <div class="u-form u-form-1">
                        <form method="POST" class="u-clearfix u-form-spacing-10 u-form-vertical u-inner-form" source="email" name="form" style="padding: 10px;">
                            <div class="u-container-style u-group u-palette-1-base u-radius-10 u-shape-round u-group-2">
                                <div class="u-container-layout u-container-layout-2">
                                    <div class="u-expanded-width u-form u-form-2">
                                        <form method="POST" class="u-clearfix u-form-spacing-10 u-form-vertical u-inner-form" source="email" name="form-1" style="padding: 10px;">
                                            @foreach (var team in Model)
                                            {
                                                <div class="u-form-email u-form-group">
                                                    <label for="email-8673" class="u-label">Name: </label>
                                                    <input type="text" placeholder="@team.Name" name="Name" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required="" spellcheck="false">
                                                </div>
                                                <div class="u-form-email u-form-group">
                                                    <label for="email-8673" class="u-label">AgeSection: @team.AgeSection</label>
                                                    <input type="number" placeholder="@team.AgeSection" id="date-e1ab" name="AgeSection" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required="">
                                                </div>
                                                <div class="u-form-email u-form-group">
                                                    @foreach (var player in players)
                                                    {
                                                        <label class="u-label">Player: @player.Name</label>
                                                        <a asp-controller="Player" asp-action="Remove" asp-route-id="@player.Id">Remove</a>
                                                        <a asp-controller="Player" asp-action="Edit" asp-route-id="@player.Id">Edit</a>
                                                    }
                                                </div>
                                                <input name="UserId" type="hidden" value="@userId" />
                                                <input name="MatchId" type="hidden" value="There is no match id on this view!" />
                                            }
                                            <div class="u-align-center u-form-group u-form-submit">
                                                <button id="login-submit" type="submit" class="w-100 btn btn-lg btn-primary">Edit</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
  </body>

SoftwareUniversity_WebApp/Views/Team/Remove.cshtml
@using WebApp.Core.Interfaces

@{
    ViewData["Title"] = "Player Remove";
}
@model IQueryable<WebApp.Core.Models.TeamViewModel>

<link rel="stylesheet" href="/css/Team/nicepage.css" media="screen" asp-append-version="true" >
<link rel="stylesheet" href="/css/Team/AddTeam.css" media="screen" asp-append-version="true">

<body class="u-body u-xl-mode">
    <section class="u-clearfix u-section-1" id="sec-9bb9">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-container-style u-expanded-width u-group u-shape-rectangle u-group-1">
          <div class="u-container-layout u-container-layout-1">
            <div class="u-form u-form-1">
              <form method="POST" class="u-clearfix u-form-spacing-10 u-form-vertical u-inner-form" source="email" name="form" style="padding: 10px;">
              <div class="u-container-style u-group u-palette-1-base u-radius-10 u-shape-round u-group-2">
                <div class="u-container-layout u-container-layout-2">
                  <div class="u-expanded-width u-form u-form-2">
                    <form method="POST" class="u-clearfix u-form-spacing-10 u-form-vertical u-inner-form" source="email" name="form-1" style="padding: 10px;">
                      @foreach (var team in Model)
                      {
                          <div class="u-form-email u-form-group">
                              <label for="email-8673" class="u-label">Name: </label>
                              <label for="email-8673" class="u-label">@team.Name</label>
                          </div>
                          <div class="u-form-email u-form-group">
                              <label for="email-8673" class="u-label">AgeSection: </label>
                              <label for="email-8673" class="u-label">@team.AgeSection</label>
                          </div>
                          <input name="Id" type="hidden" value="@team.Id" />
                          <div class="u-align-center u-form-group u-form-submit">
                              <button id="login-submit" type="submit" class="w-100 btn btn-lg btn-primary">Remove</button>
                          </div>
                      }
                    </form>
                  </div>
                </div>
              </div>
              </form>
              
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>

SoftwareUniversity_WebApp/Views/Team/ViewInfo.cshtml
@using WebApp.Core.Interfaces
@using WebApp.Core.Models

@{
    ViewData["Title"] = "Team ViewInfo";
    IEnumerable<PlayerViewModel> players = ViewData["players"] as IEnumerable<PlayerViewModel>;
}
@model IQueryable<WebApp.Core.Models.TeamViewModel>

<link rel="stylesheet" href="/css/Team/nicepage.css" media="screen" asp-append-version="true" >
<link rel="stylesheet" href="/css/Team/AddTeam.css" media="screen" asp-append-version="true">

<body class="u-body u-xl-mode">
    <section class="u-clearfix u-section-1" id="sec-9bb9">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-container-style u-expanded-width u-group u-shape-rectangle u-group-1">
          <div class="u-container-layout u-container-layout-1">
            <div class="u-form u-form-1">
              <form class="u-clearfix u-form-spacing-10 u-form-vertical u-inner-form" source="email" name="form" style="padding: 10px;">
                  <div class="u-container-style u-group u-palette-1-base u-radius-10 u-shape-round u-group-2">
                      <div class="u-container-layout u-container-layout-2">
                          <div class="u-expanded-width u-form u-form-2">
                              <form class="u-clearfix u-form-spacing-10 u-form-vertical u-inner-form" source="email" name="form-1" style="padding: 10px;">
                                  @foreach (var team in Model)
                                  {
                                      <div class="u-form-email u-form-group">
                                          <label for="email-8673" class="u-label">Name: </label>
                                          <label for="email-8673" class="u-label">@team.Name</label>
                                      </div>
                                      <div class="u-form-email u-form-group">
                                          <label for="email-8673" class="u-label">BD: </label>
                                          <label for="email-8673" class="u-label">@team.AgeSection</label>
                                      </div>

                                      <div class="u-palette-1-base u-radius-10 u-shape u-shape-round u-shape-3">
                                          <a asp-controller="Team" asp-action="Edit" asp-route-id="@team.Id">Edit</a>
                                          <a asp-controller="Team" asp-action="Remove" asp-route-id="@team.Id">Remove</a>
                                      </div>

                                      foreach (PlayerViewModel player in players)
                                      {
                                          <div class="u-form-email u-form-group">
                                              <label for="email-8673" class="u-label">Name: </label>
                                              <label for="email-8673" class="u-label">@player.Name</label>
                                          </div>
                                      }
                                  }
                              </form>
                          </div>
                      </div>
                  </div>
              </form>
              
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>