SoftwareUniversity_WebApp/Controllers/EventController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SoftwareUniversity_WebApp.Models;
using WebApp.Core.Interfaces;
using WebApp.Core.Models;

namespace SoftwareUniversity_WebApp.Controllers
{
    public class EventController : Controller
    {
        private readonly IRepository _repository;
        private readonly IEventService _eventService;
        private readonly ITeamService _tenantService;
        private readonly ITrainingService _trainingService;
        private readonly IValidationService _validator;
        private readonly UserManager<IdentityUser> _userManager;

        public EventController(IRepository repository, IEventService eventService, UserManager<IdentityUser> userManager, IPlayerService playerService, ITrainingService trainingService, ITeamService tenantService, IValidationService validator)
        {
            _repository = repository;
            _eventService = eventService;
            _userManager = userManager;
            _trainingService = trainingService;
            _tenantService = tenantService;
            _validator = validator;
        }

        public IActionResult Add()
        {
            var user = _userManager.GetUserAsync(User);
            var userId = user.Result.Id;
            var dbViewModels = _repository.GetEntitiesFromDb(userId);

            return View(dbViewModels);
        }

        [HttpPost]
        public IActionResult Add(AddEventViewModel model)
        {
            (bool passed1, string error1) = _validator.ValidateModel(model);
            if (ModelState.IsValid)
            {
                if (_eventService.CreateEvent(model))
                {
                    return RedirectToAction("Home", "Home");
                }

                return RedirectToAction("Error", "Home", new { error1 });
            }

            return RedirectToAction("Error", "Home", new { error1 });
        }

        public IActionResult ViewInfo(string id)
        {
            var eventmodeel = _eventService.FindEvent(id);

            return View(eventmodeel);
        }

        public IActionResult Edit(string id)
        {
            var user = _userManager.GetUserAsync(User);
            var userId = user.Result.Id;

            var eventt = _eventService.FindEvent(id);
            ViewData["teams"] = _tenantService.GetTeams(userId);
            ViewData["trainings"] = _trainingService.GetTrainings();
            return View(eventt);
        }

        [HttpPost]
        public IActionResult Edit(EventViewModel model)
        {
            (bool passed1, string error1) = _validator.ValidateModel(model);
            if (ModelState.IsValid)
            {
                if (_eventService.EditEvent(model))
                {
                    return RedirectToAction("Home", "Home");

                }
                return RedirectToAction("Error", "Home", new { error1 });

            }
            return RedirectToAction("Error", "Home", new { error1 });
        }

        public IActionResult Remove(string id)
        {
            var eventt = _eventService.FindEvent(id);
            return View(eventt);
        }

        [HttpPost]
        public IActionResult Remove(EventViewModel model)
        {
            if (_eventService.RemoveEvent(model.Id))
            {
                return RedirectToAction("Home", "Home");
            }
            return RedirectToAction("Error", "Home");
        }
    }
}

SoftwareUniversity_WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SoftwareUniversity_WebApp.Models;
using System.Diagnostics;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using WebApp.Core.Interfaces;
using WebApp.Infrastructure.Data;
using WebApp.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Identity;

namespace SoftwareUniversity_WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRepository _repository;
        private readonly UserManager<IdentityUser> _userManager;

        public HomeController(ILogger<HomeController> logger, IRepository repository, UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _repository = repository;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Home()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var homeModel = _repository.GetEntitiesFromDb(userId);
            return View(homeModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(string error1)
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier, Message = error1 });
        }
    }
}

SoftwareUniversity_WebApp/Controllers/MatchController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SoftwareUniversity_WebApp.Models;
using WebApp.Core.Interfaces;
using WebApp.Core.Models;

namespace SoftwareUniversity_WebApp.Controllers
{
    public class MatchController : Controller
    {
        private readonly IMatchService _matchService;
        private readonly IRepository _repository;
        private readonly ITeamService _tenantService;
        private readonly IValidationService _validator;
        private readonly UserManager<IdentityUser> _userManager;

        public MatchController(IMatchService matchService, IRepository repository, UserManager<IdentityUser> userManager, ITeamService tenantService, IValidationService validator)
        {
            _matchService = matchService;
            _repository = repository;
            _userManager = userManager;
            _tenantService = tenantService;
            _validator = validator;
        }

        public IActionResult Add()
        {
            var user = _userManager.GetUserAsync(User);
            var userId = user.Result.Id;
            var dbEntities = _repository.GetEntitiesFromDb(userId);

            return View(dbEntities);
        }

        [HttpPost]
        public IActionResult Add(AddMatchViewModel model)
        {
            (bool passed1, string error1) = _validator.ValidateModel(model);
            if (ModelState.IsValid)
            {
                if (_matchService.CreateMatch(model))
                {
                    return RedirectToAction("Home", "Home");
                }

                return RedirectToAction("Error", "Home", new { error1 });
            }

            return RedirectToAction("Error", "Home", new { error1 });
        }

        public IActionResult ViewInfo(string id)
        {
            var matchModel = _matchService.FindMatch(id);

            return View(matchModel);
        }

        public IActionResult Edit(string id)
        {
            var user = _userManager.GetUserAsync(User);
            var userId = user.Result.Id;

            var match = _matchService.FindMatch(id);
            ViewData["teams"] = _tenantService.GetTeams(userId);

            return View(match);
        }

        [HttpPost]
        public IActionResult Edit(AddMatchViewModel model)
        {
            (bool passed1, string error1) = _validator.ValidateModel(model);
            if (ModelState.IsValid)
            {
                if (_matchService.EditMatch(model))
                {
                    return RedirectToAction("Home", "Home");

                }
                return RedirectToAction("Error", "Home", new { error1 });

            }
            return RedirectToAction("Error", "Home", new { error1 });
        }

        public IActionResult Remove(string id)
        {
            var match = _matchService.FindMatch(id);

            return View(match);
        }

        [HttpPost]
        public IActionResult Remove(MatchViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (_matchService.RemoveMatch(model))
                {
                    return RedirectToAction("Home", "Home");

                }
                return RedirectToAction("Error", "Home");

            }
            return RedirectToAction("Error", "Home");
        }
    }
}

SoftwareUniversity_WebApp/Controllers/TeamController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApp.Core.Interfaces;
using WebApp.Core.Models;

namespace SoftwareUniversity_WebApp.Controllers
{
    public class TeamController : Controller
    {
        private readonly ITeamService _teamService;
        private readonly IPlayerService _playerService;
        private readonly IValidationService _validator;
        private readonly UserManager<IdentityUser> _userManager;

        public TeamController(ITeamService teamService, UserManager<IdentityUser> userManager, IPlayerService playerService, IValidationService validator)
        {
            _teamService = teamService;
            _userManager = userManager;
            _playerService = playerService;
            _validator = validator;
        }
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddTeamViewModel model)
        {
            (bool passed1, string error1) = _validator.ValidateModel(model);
            if (ModelState.IsValid)
            {
                (bool passed, string error) = _teamService.CreateTeam(model);

                if (passed = true)
                {
                    return RedirectToAction("Home", "Home");
                }
                else
                {
                    return RedirectToAction("Error", "Home", new { error1 });
                }
            }
            else
            {
                return RedirectToAction("Error", "Home", new { error1 });
            }
        }

        public IActionResult ViewInfo(string id)
        {
            var team = _teamService.FindTeam(id);
            ViewData["players"] = _playerService.GetPlayersByTeam(id);

            return View(team);
        }

        public IActionResult Edit(string id)
        {
            var team = _teamService.FindTeam(id);
            ViewData["players"] = _playerService.GetPlayersByTeam(id);
            return View(team);
        }

        [HttpPost]
        public IActionResult Edit(TeamViewModel model)
        {
            (bool passed1, string error1) = _validator.ValidateModel(model);
            if (ModelState.IsValid)
            {
                if (_teamService.EditTeam(model))
                {
                    return RedirectToAction("Home", "Home");

                }
                return RedirectToAction("Error", "Home", new { error1 });

            }
            return RedirectToAction("Error", "Home", new { error1 });
        }

        public IActionResult Remove(string id)
        {
            var team = _teamService.FindTeam(id);
            return View(team);
        }

        [HttpPost]
        public IActionResult Remove(TeamViewModel model)
        {
            if (_teamService.RemoveTeam(model.Id))
            {
                return RedirectToAction("Home", "Home");
            }
            return RedirectToAction("Error", "Home");
        }
    }
}

SoftwareUniversity_WebApp/Controllers/TrainController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using SoftwareUniversity_WebApp.Models;
using WebApp.Core.Interfaces;
using WebApp.Core.Models;

namespace SoftwareUniversity_WebApp.Controllers
{
    public class TrainController : Controller
    {
        private readonly ITeamService _teamService;
        private readonly ITrainingService _trainingService;
        private readonly IValidationService _validator;

        public TrainController(ITeamService teamService, ITrainingService trainingService, IValidationService validator)
        {
            _teamService = teamService;
            _trainingService = trainingService;
            _validator = validator;
        }
        public IActionResult Add()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var teams = _teamService.GetTeams(userId);
            return View(teams);
        }

        [HttpPost]
        public IActionResult Add(AddTrainingViewModel model)
        {
            (bool passed1, string error1) = _validator.ValidateModel(model);
            if (ModelState.IsValid)
            {
                if (_trainingService.CreateTrainig(model))
                {
                    return RedirectToAction("Home", "Home");

                }
                return RedirectToAction("Error", "Home", new { error1 });

            }
            return RedirectToAction("Error", "Home", new { error1 });
        }

        public IActionResult ViewInfo(string id)
        {
            var train = _trainingService.FindTraining(id);
            return View(train);
        }

        public IActionResult Edit(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var teams = _teamService.GetTeams(userId);
            ViewData["train"] = _trainingService.FindTraining(id);
            return View(teams);
        }

        [HttpPost]
        public IActionResult Edit(TrainingViewModel model)
        {
            (bool passed1, string error1) = _validator.ValidateModel(model);
            if (ModelState.IsValid)
            {
                if (_trainingService.EditTraining(model))
                {
                    return RedirectToAction("Home", "Home");

                }
                return RedirectToAction("Error", "Home", new { error1 });

            }
            return RedirectToAction("Error", "Home", new { error1 });
        }

        public IActionResult Remove(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var training = _trainingService.FindTraining(id);

            return View(training);
        }

        [HttpPost]
        public IActionResult Remove(TrainingViewModel model)
        {
            if (_trainingService.RemoveTraining(model.Id))
            {
                return RedirectToAction("Home", "Home");
            }

            return RedirectToAction("Error", "Home");
        }
    }
}

SoftwareUniversity_WebApp/Views/Home/Home.cshtml
@{
    ViewData["Title"] = "Home";
}

@model WebApp.Core.Models.HomeViewModel
@using Microsoft.AspNetCore.Identity
@using WebApp.Core.Models
@using WebApp.Infrastructure.Data.Models
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<link rel="stylesheet" href="/css/nicepageHome.css" media="screen" asp-append-version="true" >
<link rel="stylesheet" href="/css/Home.css" media="screen" asp-append-version="true">
    
    @if (SignInManager.IsSignedIn(User))
    {
        <body class="u-body u-xl-mode">
        <section class="u-clearfix u-section-1" id="sec-84db">
        <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-list u-list-1">
          <div class="u-repeater u-repeater-1">
              <div class="u-border-8 u-border-grey-75 u-container-style u-list-item u-palette-1-dark-1 u-repeater-item u-shape-rectangle u-list-item-1">
                  <div class="u-container-layout u-similar-container u-container-layout-1">
                      <a asp-area="" asp-controller="Team" asp-action="Add" class="u-btn u-btn-round u-button-style u-hover-feature u-hover-palette-1-light-1 u-palette-1-base u-radius-6 u-btn-2" data-animation-name="pulse" data-animation-duration="1000" data-animation-direction="">Add Team&nbsp;<span class="u-file-icon u-icon u-text-white u-icon-2"><img src="/icons/add.png" alt=""></span></a>
                      <a asp-area="" asp-controller="Player" asp-action="Add" class="u-align-center u-btn  u-button-style u-hover-feature u-hover-palette-1-light-1 u-palette-1-base u-radius-6 u-btn-1" data-animation-name="pulse" data-animation-duration="1000" data-animation-direction="">Add Player&nbsp;<span class="u-file-icon u-icon u-text-white u-icon-1"><img src="/icons/add.png" alt=""></span></a>
                      <a asp-area="" asp-controller="Train" asp-action="Add" class="u-btn u-btn-round u-button-style u-hover-feature u-hover-palette-1-light-1 u-palette-1-base u-radius-6 u-btn-5" data-animation-name="pulse" data-animation-duration="1000" data-animation-direction="">Add Training&nbsp;<span class="u-file-icon u-icon u-text-white u-icon-5"><img src="/icons/add.png" alt=""></span></a>
                      <a asp-area="" asp-controller="Event" asp-action="Add" class="u-btn u-btn-round u-button-style u-hover-feature u-hover-palette-1-light-1 u-palette-1-base u-radius-6 u-btn-3" data-animation-name="pulse" data-animation-duration="1000" data-animation-direction="">Add Event&nbsp;<span class="u-file-icon u-icon u-text-white u-icon-3"><img src="/icons/add.png" alt=""></span></a>
                      <a asp-area="" asp-controller="Match" asp-action="Add" class="u-btn u-btn-round u-button-style u-hover-feature u-hover-palette-1-light-1 u-palette-1-base u-radius-6 u-btn-3" data-animation-name="pulse" data-animation-duration="1000" data-animation-direction="">Add Match&nbsp;<span class="u-file-icon u-icon u-text-white u-icon-3"><img src="/icons/train.png" alt=""></span></a>
                  </div>
              </div>
              <div class="u-border-8 u-border-grey-75 u-container-style u-list-item u-palette-1-dark-1 u-repeater-item u-shape-rectangle u-list-item-1">
                  <div class="u-container-layout u-similar-container u-container-layout-1">
                      <center><label>Matches</label></center>
                      @foreach (var macthViewModel in Model.MatchViewModels)
                      {
                          @if(macthViewModel.Team1 != null || macthViewModel.Team2 != null)
                          {
                              <div>
                                  <center><a asp-controller="Match" asp-action="ViewInfo" asp-route-id="@macthViewModel.Id">@macthViewModel.Team1.Name VS @macthViewModel.Team2.Name</a></center>
                              </div>
                          }
                          else
                          {
                              <div>
                                  <center><label for="date-e1ab" class="u-label">There Are No Matches Yet!</label></center>
                              </div>
                          }
                      }
                  </div>
              </div>
          </div>
        </div>
        <div class="u-clearfix u-gutter-20 u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-size-30">
                <div class="u-layout-col">
                  <div class="u-align-left u-container-style u-layout-cell u-palette-1-dark-1 u-shape-rectangle u-size-60 u-layout-cell-1">
                      <div class="u-border-20 u-border-grey-75 u-container-layout u-container-layout-2">
                          <center><label>Players</label></center>
                          @if (Model.PlayerViewModels.Count() == 0)
                          {
                              <div class="u-palette-1-base u-radius-10 u-shape u-shape-round u-shape-3">
                                  <center>There Are No Players Yet!</center>
                              </div>
                          }
                          else
                          {

                              @foreach (var playerModel in Model.PlayerViewModels)
                              {
                                  <div class="u-palette-1-base u-radius-10 u-shape u-shape-round u-shape-3">
                                      <center><a asp-controller="Player" asp-action="ViewInfo" asp-route-id="@playerModel.Id">@playerModel.Name</a></center>

                                      @*@Html.ActionLink(playerModel.Name, "ViewInfo", "Player", new {playerModel})*@
                                  </div>
                              }
                          }
                      </div>
                  </div>
                </div>
              </div>
              <div class="u-size-30">
                <div class="u-layout-col">
                  <div class="u-container-style u-layout-cell u-palette-1-dark-1 u-shape-rectangle u-size-30 u-layout-cell-2">
                      <div class="u-border-20 u-border-grey-75 u-container-layout u-container-layout-3">
                          <center><label>Teams</label></center>
                          @if (Model.TeamViewModels.Count() == 0)
                          {
                              <div class="u-palette-1-base u-radius-10 u-shape u-shape-round u-shape-1">
                                  <center><label for="date-e1ab" class="u-label">There Are No Teams Yet!</label></center>
                              </div>
                          }
                          else
                          {

                              @foreach (var teamModel in Model.TeamViewModels)
                              {
                                  <div class="u-palette-1-base u-radius-10 u-shape u-shape-round u-shape-1">
                                      <center><a asp-controller="Team" asp-action="ViewInfo" asp-route-id="@teamModel.Id">@teamModel.Name</a></center>
                                  </div>
                              }
                          }
                      </div>
                  </div>
                    <div class="u-container-style u-layout-cell u-palette-1-dark-1 u-shape-rectangle u-size-30 u-layout-cell-3">
                        <div class="u-border-20 u-border-grey-75 u-container-layout u-container-layout-4">
                            <center><label>Trainings</label></center>
                            @if (Model.TrainingViewModels.Count() == 0)
                            {
                                <div class="u-palette-1-base u-radius-10 u-shape u-shape-round u-shape-5">
                                    <center>There Are No Trainigs Yet!</center>
                                </div>
                            }
                            else
                            {

                                @foreach (var trainigModel in Model.TrainingViewModels)
                                {
                                    
                                        <div class="u-palette-1-base u-radius-10 u-shape u-shape-round u-shape-5">
                                            <div class="u-palette-1-base u-radius-10 u-shape u-shape-round u-shape-3">
                                                <center><a asp-controller="Train" asp-action="ViewInfo" asp-route-id="@trainigModel.Id">@trainigModel.Type - @trainigModel.Description</a></center>
                                            </div>
                                        </div>   
                                    
                                }
                            }
                        </div>
                    </div>
                    <div class="u-container-style u-layout-cell u-palette-1-dark-1 u-shape-rectangle u-size-30 u-layout-cell-3">
                        <div class="u-border-20 u-border-grey-75 u-container-layout u-container-layout-4">
                            <center><label>Events</label></center>
                            @if (Model.EventViewModels.Count() == 0)
                            {
                                <div class="u-palette-1-base u-radius-10 u-shape u-shape-round u-shape-5">
                                    <center>There Are No Events Yet!</center>
                                </div>
                            }
                            else
                            {

                                @foreach (var eventViewModel in Model.EventViewModels)
                                {
                                    <div class="u-palette-1-base u-radius-10 u-shape u-shape-round u-shape-5">
                                        <div class="u-palette-1-base u-radius-10 u-shape u-shape-round u-shape-3">
                                            <center><a asp-controller="Event" asp-action="ViewInfo" asp-route-id="@eventViewModel.Id">@eventViewModel.Name - @eventViewModel.Type</a></center>
                                        </div>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
         </div>
        </section>
        </body>
    }
else
{
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Welcome to Co-Coach">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>Home</title>
    <link rel="stylesheet" href="/css/nicepage.css" media="screen" asp-append-version="true" >
    <link rel="stylesheet" href="/css/index.css" media="screen" asp-append-version="true">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>Home</title>
    
    <link rel="stylesheet" href="/css/nicepageHome.css" media="screen" asp-append-version="true" >
    <link rel="stylesheet" href="/css/Home.css" media="screen" asp-append-version="true">

    <meta name="generator" content="Nicepage 4.6.9, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="Home">
    <meta property="og:type" content="website">
    <link rel="canonical" href="/">
    
    <meta name="generator" content="Nicepage 4.6.9, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
</head>

<body class="u-body u-xl-mode">
    <section class="skrollable skrollable-between u-align-center u-clearfix u-gradient u-section-1" id="sec-7c7a">
        <div class="u-clearfix u-sheet u-sheet-1">
            <h1 class="u-text u-text-body-alt-color u-text-default u-title u-text-1" spellcheck="false"><b>Welcome to Co-Coach</b>
            </h1>
        </div>
    </section>
    </body>
}

SoftwareUniversity_WebApp/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Home Page";
}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Welcome to Co-Coach">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>Home</title>
    <link rel="stylesheet" href="/css/nicepage.css" media="screen" asp-append-version="true" >
    <link rel="stylesheet" href="/css/index.css" media="screen" asp-append-version="true">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>Home</title>
    
    <link rel="stylesheet" href="/css/nicepageHome.css" media="screen" asp-append-version="true" >
    <link rel="stylesheet" href="/css/Home.css" media="screen" asp-append-version="true">

    <meta name="generator" content="Nicepage 4.6.9, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="Home">
    <meta property="og:type" content="website">
    <link rel="canonical" href="/">
    
    <meta name="generator" content="Nicepage 4.6.9, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
</head>

<body class="u-body u-xl-mode">
    <section class="skrollable skrollable-between u-align-center u-clearfix u-gradient u-section-1" id="sec-7c7a">
        <div class="u-clearfix u-sheet u-sheet-1">
            <h1 class="u-text u-text-body-alt-color u-text-default u-title u-text-1" spellcheck="false"><b>Welcome to Co-Coach</b>
            </h1>
        </div>
    </section>
    </body>